import Link from "next/link";
import Head from "next/head";
import CourseList from "@/components/CourseList";

export default function Courses() {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <CourseList/>
            </main>
        </>
    )
}