import Link from "next/link";
import Head from "next/head";
import styles from '@/styles/FreeBooks.module.css'
import React, {useState} from "react";

const fetcher = (url: string) => fetch(url).then(r => r.json())

export default function FreeBooks() {

    interface BookData {
        id: number;
        title: string;
        author: string | null;
        imageURL: string | undefined;
        epubURL: string | null;
        pdfURL: string | null;
    }

    const [currentSubject, setCurrentSubject] = useState<string>('choose')
    const [books, setBooks] = useState<BookData[] | null>(null)


    const updateBooks = async () => {
        if (currentSubject === 'choose') return
        const data = await fetch(`http://gutendex.com/books/?topic=${currentSubject}`)
            .then((response) => response.json())
        const newBooks = data.results.map((book: any) => {
            return {
                id: book.id,
                title: book.title,
                author: book.authors.length > 0 ? book.authors[0].name : null,
                imageURL: book.formats['image/jpeg'] ? book.formats['image/jpeg'] : undefined,
                epubURL: book.formats['application/epub+zip']
                    ? book.formats['application/epub+zip'] : null,
                pdfURL : book.formats['application/pdf'] ? book.formats['application/pdf'] : null
            }
        })
        setBooks(newBooks)
    }

    const handleSubjectChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        setCurrentSubject(e.target.value);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.container}>
                    <h1 className={styles.pageTitle}>
                        Project Gutenberg Free Books
                    </h1>
                    <div className={styles.controls}>
                        <select
                            value={currentSubject}
                            onChange={handleSubjectChange}
                            className={styles.subjectSelector}
                        >
                            <option value={'choose'}>Choose Subject</option>
                            <option value={'mathematics'}>Mathematics</option>
                            <option value={'biology'}>Biology</option>
                            <option value={'physics'}>Physics</option>
                            <option value={'chemistry'}>Chemistry</option>
                            <option value={'physiology'}>Physiology</option>
                            <option value={'microbiology'}>Microbiology</option>
                        </select>
                        <button
                            onClick={updateBooks}
                            className={styles.getNewBooksButton}
                        >
                            Get Books</button>
                    </div>
                    <ul>
                        {books?.map(book => (
                            <div key={book.id} className={styles.bookItem}>
                                <div className={styles.nonImageContent}>
                                    <h2>
                                        {book.title}
                                    </h2>
                                    <h4>
                                        {book.author}
                                    </h4>
                                    <div className={styles.postingOptions}>
                                        {book.epubURL &&
                                            <a
                                                href={book.epubURL}
                                                className={styles.postingOption}
                                            >
                                                Epub
                                            </a>
                                        }
                                        {book.pdfURL &&
                                            <a
                                                href={book.pdfURL}
                                                target="_blank"
                                                className={styles.postingOption}
                                            >
                                                PDF
                                            </a>
                                        }
                                    </div>
                                </div>
                                <img src={book.imageURL} alt="test" className={styles.bookImage}/>
                            </div>
                        ))}
                    </ul>
                </div>
                <Link href={`/`}>Back to Home</Link>
            </main>
        </>
    )

}